server:
  port: 8081

spring:
  application:
    name: user_check

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/user_check
    username: root
    password: gkwlak98

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

    generate-ddl: true
