server:
  port: 80

  application:

    name: user_check

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        default_batch_fetch_size: 100
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: false



#logging:
#  level:
#    org.hibernate.orm.jdbc.bind: trace