spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:usercheck;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 100
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: false
  cache:
    type: simple
  data:
    redis:
      host: localhost
      port: 6379
      password: test-redis-password
  jwt:
    secret: sOX6rwX65uDe+JphKfE9SAbC9oR3n61BN84t9zkN9QI=
  kafka:
    producer:
      acks: all
      retries: 1
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
        delivery.timeout.ms: 30000
        request.timeout.ms: 10000
        retry.backoff.ms: 100
    bootstrap-servers:
      - localhost:9092
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="test-user" password="test-password";
  ai:
    openai:
      api-key: test-api-key
  elasticsearch:
    server-url: http://localhost:9200
    username: test-elastic-user
    password: test-elastic-password
