spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${SPRING_USERCHECK_DATASOURCE_USERNAME}
    password: ${SPRING_USERCHECK_DATASOURCE_PASSWORD}
    url: ${SPRING_USERCHECK_DATASOURCE_URL:jdbc:mariadb://localhost:3307/user_check?rewriteBatchedStatements=true}

  jwt:
    secret: ${SPRING_USERCHECK_JWT_KEY}

  application:
    name: user_check

  cache:
    type: redis

  data:
    redis:
      host: ${SPRING_CACHE_DB_HOST:localhost}
      port: ${SPRING_CACHE_DB_PORT:6379}

  kafka:
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        retry.backoff.ms: 1000
    bootstrap-servers:
      - ${KAFKA_1_SERVER:localhost:9092}
      - ${KAFKA_2_SERVER:localhost:9093}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small

  elasticsearch:
    server-url: ${ELASTICSEARCH_SERVER_URL:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}

springdoc:
  use-fqn: true
  api-docs:
    path: /docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    default-models-expand-depth: -1
    operations-sorter: alpha
    tags-sorter: alpha
    path: /docs/swagger-ui
    disable-swagger-default-url: true
  paths-to-match:
    - /**

access-token-expiration-time: 5
refresh-token-expiration-time: 1440

management:
  endpoints:
    web:
      exposure:
        include: health, beans, httptrace, info, metrics, prometheus
