server:
  port: 8081

  application:
    name: user_check

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true